[package]
name = "small_sorted_set"
license = "GPL-3.0-or-later"
description = "A `SmallVec`-backed, sorted vec, with no duplicate elements"
documentation = "https://docs.rs/small_sorted_set"
repository = "https://github.com/BigWingBeat/small_sorted_set"
keywords = ["vector", "vec", "stack", "no_std", "small"]
categories = ["data-structures"]
version = "1.0.1"
edition = "2024"
rust-version = "1.85"

[features]
serde = ["dep:serde", "smallvec/serde"]

[dependencies]
smallvec = { version = "1.16", features = ["union", "const_generics"] }
serde = { version = "1.0", optional = true, default-features = false }
