[package]
name = "small_sorted_set"
license = "GPL-3.0-or-later"
description = "A `SmallVec`-backed, sorted vec, with no duplicate elements"
documentation = "https://docs.rs/small_sorted_set"
repository = "https://github.com/BigWingBeat/small_sorted_set"
keywords = ["vector", "vec", "stack", "no_std", "small"]
categories = ["data-structures"]
version = "0.1.0"
edition = "2024"

[dependencies]
smallvec = { version = "1.16", features = ["union", "const_generics", "const_new"] }
